#import <Foundation/Foundation.h>

// ! Project version number
FOUNDATION_EXPORT double opencv2VersionNumber;

// ! Project version string
FOUNDATION_EXPORT const unsigned char opencv2VersionString[];

#import <ArrayUtil.h>
#import <ByteVector.h>
#import <CVObjcUtil.h>
#import <Converters.h>
#import <CvType.h>
#import <DMatch.h>
#import <Double2.h>
#import <Double3.h>
#import <DoubleVector.h>
#import <Float4.h>
#import <Float6.h>
#import <FloatVector.h>
#import <Int4.h>
#import <IntVector.h>
#import <KeyPoint.h>
#import <Mat.h>
#import <MatOfByte.h>
#import <MatOfDMatch.h>
#import <MatOfDouble.h>
#import <MatOfFloat.h>
#import <MatOfFloat4.h>
#import <MatOfFloat6.h>
#import <MatOfInt.h>
#import <MatOfInt4.h>
#import <MatOfKeyPoint.h>
#import <MatOfPoint2f.h>
#import <MatOfPoint2i.h>
#import <MatOfPoint3.h>
#import <MatOfPoint3f.h>
#import <MatOfRect2d.h>
#import <MatOfRect2i.h>
#import <MatOfRotatedRect.h>
#import <MinMaxLocResult.h>
#import <Point2d.h>
#import <Point2f.h>
#import <Point2i.h>
#import <Point3d.h>
#import <Point3f.h>
#import <Point3i.h>
#import <Range.h>
#import <Rect2d.h>
#import <Rect2f.h>
#import <Rect2i.h>
#import <RotatedRect.h>
#import <Scalar.h>
#import <Size2d.h>
#import <Size2f.h>
#import <Size2i.h>
#import <TermCriteria.h>
#import <Core.h>
#import <Algorithm.h>
#import <TickMeter.h>
#import <Moments.h>
#import <Imgproc.h>
#import <CLAHE.h>
#import <GeneralizedHough.h>
#import <GeneralizedHoughBallard.h>
#import <GeneralizedHoughGuil.h>
#import <LineSegmentDetector.h>
#import <Subdiv2D.h>
#import <IntelligentScissorsMB.h>
#import <Ml.h>
#import <ANN_MLP.h>
#import <Boost.h>
#import <DTrees.h>
#import <EM.h>
#import <KNearest.h>
#import <LogisticRegression.h>
#import <NormalBayesClassifier.h>
#import <ParamGrid.h>
#import <RTrees.h>
#import <SVM.h>
#import <SVMSGD.h>
#import <StatModel.h>
#import <TrainData.h>
#import <Photo.h>
#import <AlignExposures.h>
#import <AlignMTB.h>
#import <CalibrateCRF.h>
#import <CalibrateDebevec.h>
#import <CalibrateRobertson.h>
#import <MergeDebevec.h>
#import <MergeExposures.h>
#import <MergeMertens.h>
#import <MergeRobertson.h>
#import <Tonemap.h>
#import <TonemapDrago.h>
#import <TonemapMantiuk.h>
#import <TonemapReinhard.h>
#import <Dnn.h>
#import <ClassificationModel.h>
#import <DetectionModel.h>
#import <DictValue.h>
#import <KeypointsModel.h>
#import <Layer.h>
#import <Model.h>
#import <Net.h>
#import <SegmentationModel.h>
#import <TextDetectionModel.h>
#import <TextDetectionModel_DB.h>
#import <TextDetectionModel_EAST.h>
#import <TextRecognitionModel.h>
#import <Features2d.h>
#import <AKAZE.h>
#import <AffineFeature.h>
#import <AgastFeatureDetector.h>
#import <BFMatcher.h>
#import <BOWImgDescriptorExtractor.h>
#import <BOWKMeansTrainer.h>
#import <BOWTrainer.h>
#import <BRISK.h>
#import <DescriptorMatcher.h>
#import <FastFeatureDetector.h>
#import <Feature2D.h>
#import <FlannBasedMatcher.h>
#import <GFTTDetector.h>
#import <KAZE.h>
#import <MSER.h>
#import <ORB.h>
#import <SIFT.h>
#import <SimpleBlobDetector.h>
#import <SimpleBlobDetectorParams.h>
#import <Mat+Converters.h>
#import <Imgcodecs.h>
#import <CvCamera2.h>
#import <Videoio.h>
#import <VideoCapture.h>
#import <VideoWriter.h>
#import <Calib3d.h>
#import <CirclesGridFinderParameters.h>
#import <StereoBM.h>
#import <StereoMatcher.h>
#import <StereoSGBM.h>
#import <UsacParams.h>
#import <Objdetect.h>
#import <BaseCascadeClassifier.h>
#import <CascadeClassifier.h>
#import <HOGDescriptor.h>
#import <QRCodeDetector.h>
#import <Video.h>
#import <BackgroundSubtractor.h>
#import <BackgroundSubtractorKNN.h>
#import <BackgroundSubtractorMOG2.h>
#import <DISOpticalFlow.h>
#import <DenseOpticalFlow.h>
#import <FarnebackOpticalFlow.h>
#import <KalmanFilter.h>
#import <SparseOpticalFlow.h>
#import <SparsePyrLKOpticalFlow.h>
#import <Tracker.h>
#import <TrackerDaSiamRPN.h>
#import <TrackerDaSiamRPNParams.h>
#import <TrackerGOTURN.h>
#import <TrackerGOTURNParams.h>
#import <TrackerMIL.h>
#import <TrackerMILParams.h>
#import <VariationalRefinement.h>